# Generated by Django 5.2.17 on 2026-08-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('client_organisation', models.CharField(help_text='Client ou Organisme ayant délivré le document', max_length=200)),
                ('type', models.CharField(choices=[('attestation', 'Attestation'), ('certificate', 'Certificat'), ('reference', 'Référence'), ('other', 'Autre')], default='attestation', max_length=20)),
                ('date', models.CharField(blank=True, help_text='Date ou période indiquée sur le document', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Contexte ou détails du document')),
                ('image', models.ImageField(blank=True, null=True, upload_to='attestations/images/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='attestations/pdf/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
