# Generated by Django 5.2.17 on 2026-08-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='J&B SANIYAPUR SARL', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('tagline', models.CharField(default='PROPRETÉ SUR ORDONNANCE', help_text='Devise officielle — ne pas modifier sans demande explicite.', max_length=200)),
                ('slogan', models.CharField(default='La propreté et l’hygiène qui protègent, la qualité qui rassure.', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('hero_title', models.CharField(blank=True, max_length=300)),
                ('hero_text', models.TextField(blank=True)),
                ('hero_primary_button_label', models.CharField(blank=True, max_length=80)),
                ('hero_primary_button_url', models.CharField(blank=True, max_length=200)),
                ('hero_secondary_button_label', models.CharField(blank=True, max_length=80)),
                ('hero_secondary_button_url', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
