# Generated by Django 5.2.17 on 2026-08-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_title', models.CharField(default='Présentation de J&B SANIYAPUR', max_length=200)),
                ('presentation_content', models.TextField(default='Société spécialisée dans la maintenance immobilière, le nettoyage industriel et le bionettoyage, J&B SANIYAPUR SARL intervient également en désinfection et assainissement, hygiène publique et environnementale, traitement des sanitaires et gestion des déchets industriels — au service des environnements de santé comme des environnements professionnels et industriels.\n\nImplantée à Ouagadougou et Bobo-Dioulasso, Burkina Faso, l’entreprise met son expérience de terrain au service d’organisations publiques et privées, avec une exigence constante de qualité, de méthode et de maîtrise des risques sanitaires.')),
                ('presentation_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('history_title', models.CharField(default='Notre histoire', max_length=200)),
                ('history_content', models.TextField(default="Fondée avec l'ambition d'apporter des standards professionnels et rigoureux dans le domaine de la propreté et de l'hygiène, J&B SANIYAPUR SARL s'est développée en répondant aux exigences techniques et sanitaires des entreprises et institutions au Burkina Faso.")),
                ('history_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('mission_title', models.CharField(default='Notre mission', max_length=200)),
                ('mission_content', models.TextField(default='Offrir des solutions professionnelles de propreté, d’hygiène et de maintenance qui protègent les personnes, les espaces et les activités.\n\nLa propreté et l’hygiène qui protègent, la qualité qui rassure.')),
                ('vision_title', models.CharField(default='Notre vision', max_length=200)),
                ('vision_content', models.TextField(default="Devenir le partenaire de référence au Burkina Faso et dans la sous-région dans les domaines de la maintenance immobilière, de l'hygiène professionnelle, du bionettoyage et de la gestion environnementale.")),
                ('engagements_title', models.CharField(default='Nos engagements', max_length=200)),
                ('engagements_content', models.TextField(default='L’entreprise oriente son action vers des environnements plus sûrs, plus sains et mieux maîtrisés.\n- Réduction des risques sanitaires\n- Amélioration de la sécurité et du bien-être\n- Réduction des risques de contamination\n- Préservation des équipements\n- Amélioration de l’image\n- Meilleure efficacité des activités')),
                ('expertise_title', models.CharField(default='Notre expertise', max_length=200)),
                ('expertise_content', models.TextField(default='Une approche professionnelle de la maintenance, du nettoyage et de l’hygiène, appuyée par des protocoles rigoureux et du matériel industriel adapté aux normes sanitaires.')),
                ('expertise_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('dg_name', models.CharField(blank=True, default='Directeur Général', max_length=160)),
                ('dg_role', models.CharField(blank=True, default='Directeur Général de J&B SANIYAPUR SARL', max_length=160)),
                ('dg_photo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('dg_message', models.TextField(blank=True, default='Bienvenue chez J&B SANIYAPUR SARL. Notre engagement quotidien est de vous offrir des espaces sains, sécurisés et valorisés grâce à notre rigueur et notre savoir-faire.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
