# Generated by Django 5.2.17 on 2026-08-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_aboutsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsettings',
            name='expertise_content',
        ),
        migrations.RemoveField(
            model_name='aboutsettings',
            name='expertise_image',
        ),
        migrations.RemoveField(
            model_name='aboutsettings',
            name='expertise_title',
        ),
        migrations.RemoveField(
            model_name='aboutsettings',
            name='history_content',
        ),
        migrations.RemoveField(
            model_name='aboutsettings',
            name='history_image',
        ),
        migrations.RemoveField(
            model_name='aboutsettings',
            name='history_title',
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='bionettoyage_advantages_content',
            field=models.TextField(default='Les avantages concrets du bionettoyage pour les établissements :\n- Réduire le risque d’infections.\n- Sécuriser les clients, le personnel, les consommateurs et les visiteurs.\n- Garantir une hygiène constante dans tous les services.\n- Préserver durablement les locaux et les équipements.\n- Améliorer le confort et l’expérience clients.\n- Faciliter le contrôle et la traçabilité des prestations.\n- Renforcer l’image et la confiance envers l’établissement.\n- Optimiser l’organisation du personnel.'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='bionettoyage_content',
            field=models.TextField(default='Le bionettoyage en milieu hospitalier est un processus essentiel de nettoyage et de désinfection rigoureux des surfaces et équipements pour éliminer les micro-organismes pathogènes, prévenir les infections nosocomiales et assurer un environnement sûr pour patients et personnel.\n\nPrincipes clés :\n- Définition : Combinaison de nettoyage (élimination des saletés visibles) et de désinfection (élimination des micro-organismes invisibles).\n- Objectif : Maîtriser les infections nosocomiales, crucial dans les blocs opératoires et chambres.\n- Protocole : Suivi strict par des professionnels formés.\n\nEnjeux majeurs :\n- Prévention des infections nosocomiales : Réduire la charge microbienne et protéger les patients vulnérables.\n- Protection du personnel soignant : Réduire les risques de contamination professionnelle.\n- Conformité réglementaire : Exigences des autorités sanitaires (OMS, normes ISO).\n- Image et confiance : Un hôpital propre inspire confiance aux patients et à leurs familles.'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='bionettoyage_title',
            field=models.CharField(default="L'IMPORTANCE ET LES ENJEUX DU BIONETTOYAGE", max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='competencies_content',
            field=models.TextField(default='1. Bionettoyage et désinfection\n2. Décapage et entretien des plateaux techniques\n3. Gestion des déchets industriels\n4. Produits & Équipements professionnels\n5. Formation & Placement du personnel\n6. Traitement des sanitaires\n7. Hygiène publique & environnementale'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='competencies_title',
            field=models.CharField(default='NOS DOMAINES DE COMPÉTENCES', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='international_expertise_content',
            field=models.TextField(default="Grâce au travail d’équipe avec nos groupes allemands PUTZI SAUBER SERVICE et SYLT PURE REINIGUNG, nous bénéficions de :\n- Plus de 20 ans d'expérience dans le nettoyage hospitalier en Allemagne.\n- Accès aux dernières technologies et innovations en matière de bionettoyage.\n- Formation continue de nos équipes aux standards européens.\n- Équipements et produits certifiés conformes aux normes les plus strictes.\n- Méthodologie éprouvée dans des établissements de renommée internationale.\n- Transfert de savoir-faire et de bonnes pratiques."),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='international_expertise_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='international_expertise_title',
            field=models.CharField(default='EXPERTISE INTERNATIONALE', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='objectives_content',
            field=models.TextField(default="L'objectif principal de J&B SANIYAPUR est de permettre aux établissements de santé et industriels d'exercer leurs activités dans les meilleures conditions d'hygiène, en collaboration étroite avec les professionnels pour assurer un service de qualité irréprochable."),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='objectives_title',
            field=models.CharField(default='NOTRE OBJECTIF ET OBJECTIFS SPÉCIFIQUES', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='operational_team_content',
            field=models.TextField(default="Notre équipe opérationnelle est composée de près de 100 techniciens de surface qualifiés, formés spécifiquement au bionettoyage hospitalier. Chaque membre du personnel :\n- Est déclaré à la Caisse de Sécurité Sociale.\n- Bénéficie d'une assurance maladie et de protections sociales.\n- Reçoit une formation continuous aux protocoles d'hygiène.\n- Est équipé d'EPI (Équipements de Protection Individuelle) conformes.\n- Suit des contrôles médicaux réguliers.\n- Est évalué périodiquement sur ses performances."),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='operational_team_title',
            field=models.CharField(default='LE PERSONNEL OPÉRATIONNEL', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='presentation_devise',
            field=models.TextField(default='Notre Devise : "PROPRETÉ SUR ORDONNANCE"\nJ&B SANIYAPUR s’engage à créer et maintenir des environnements propres, sains et maîtrisés, en contribuant à la protection des personnes, à la préservation des espaces et des équipements, ainsi qu’à la qualité des activités, dans les établissements de santé comme dans les environnements professionnels et industriels.'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='presentation_legal_info',
            field=models.TextField(default='Raison sociale : J&B SANIYAPUR SARL\nSecteur d’activité : Nettoyage industriel et bionettoyage de centres médicaux\nSiège social : Bobo-Dioulasso, Ouagadougou (BURKINA FASO)\nDirecteur Général : Monsieur Jules TEKPO\nContact principal : Tel : +226 06556709 / WhatsApp : +49 1727717178\nEmail : info@jb-saniyapur.com\nSite web : www.jb-saniyapur.com\nPartenaires Groupes : PUTZI SAUBER SERVICE & SYLT PURE REINIGUNG (Entreprises allemandes - www.putzi-sylt.de / www.sylt-pure.com)\nNuméro IFU : 00 288 071 F\nRCCM : BF-OUA-01-2025-B13-16674\nRIB : BF 0022022440514000160166'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='references_content',
            field=models.TextField(default="J&B SANIYAPUR, à travers ses partenariats avec les entreprises allemandes PUTZI SAUBER SERVICE et SYLT PURE REINIGUNG, a développé une expertise reconnue :\n\n1. CHU DE PALA (Bobo-Dioulasso, Burkina Faso) : Nettoyage, bionettoyage des locaux, gestion des déchets, désinfection blocs opératoires & surfaces.\n2. HÔPITAL DOGTA-LAFIÈ / CLINIQUE LE PRINTEMPS (Lomé, Togo) : Bionettoyage, désinfection, fourniture d'équipements, formation du personnel.\n3. HOTEL BUDERSAND & HOTEL A-ROSA (Sylt, Allemagne) : Entretien général, désinfection surfaces, standards hôtellerie de luxe.\n4. 411 MAISONS DE LUXE (Sylt, Allemagne) : Nettoyage, désinfection et maintenance régulière de haut standing."),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='references_title',
            field=models.CharField(default='NOS RÉFÉRENCES CLIENTS', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='social_commitment_content',
            field=models.TextField(default="Nous nous engageons à offrir les meilleures conditions de travail à nos employés, qui sont avant tout nos concitoyens. À ce titre, nous prévoyons :\n- La mise en place d'une garderie pour les enfants de nos employés.\n- Un environnement de travail sain, sûr et respectueux.\n- Des opportunités de formation et d'évolution professionnelle.\n- Une rémunération équitable et des avantages sociaux.\n- Un soutien psychologique si nécessaire (travail en milieu hospitalier)."),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='social_commitment_title',
            field=models.CharField(default='NOTRE ENGAGEMENT SOCIAL', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='specific_objectives_content',
            field=models.TextField(default="1. Maintenir la propreté dès la construction : Intervention dès la phase de construction pour préserver l'état d'origine des équipements sanitaires ou industriels.\n2. Prévenir la détérioration des équipements : Prévenir la rouille, l'usure et les fermetures d'établissements.\n3. Garantir la sécurité sanitaire : Protéger le personnel, les patients et consommateurs.\n4. Optimiser les coûts d'exploitation : Entretien préventif pour prolonger la durée de vie des équipements.\n5. Améliorer l'expérience client : Confort, bien-être et satisfaction des usagers.\n6. Valoriser l'image de l'établissement : Renforcer la confiance des clients, partenaires et autorités."),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='team_presentation_content',
            field=models.TextField(default="J&B SANIYAPUR dispose d'une équipe expérimentée et qualifiée, formée aux standards internationaux. Notre personnel est notre premier atout pour garantir un service de qualité irréprochable."),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='team_presentation_title',
            field=models.CharField(default="PRÉSENTATION DE L'ÉQUIPE DE DIRECTION ET DU PERSONNEL", max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='vision_execution_content',
            field=models.TextField(default='Comment nous réalisons cette vision :\n- Protocoles rigoureux : Application stricte et traçabilité complète.\n- Personnel hautement qualifié : Formation continue aux standards internationaux.\n- Produits et équipements de pointe : Produits certifiés bactéricides/virucides et matériel allemand.\n- Approche préventive : Intervention proactive permanente.\n- Contrôle qualité constant : Audits réguliers et contrôles microbiologiques.\n- Collaboration étroite avec les équipes hospitalières.'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='vision_impact_content',
            field=models.TextField(default='Impact direct sur la satisfaction :\n- Réduction des risques sanitaires et de contamination.\n- Amélioration de la sécurité, du confort et du bien-être.\n- Préservation des équipements et des infrastructures.\n- Amélioration de l’image et crédibilité de l’organisation.'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='vision_paradox_content',
            field=models.TextField(default='Le paradoxe que nous combattons :\nNous combattons l\'idée ironique et malheureusement trop réelle selon laquelle "on entre à l\'hôpital avec une maladie et on repart avec une autre ou plusieurs maladies". Cette expression reflète une réalité préoccupante que nous éliminons par notre bionettoyage rigoureux.'),
        ),
        migrations.AlterField(
            model_name='aboutsettings',
            name='dg_message',
            field=models.TextField(blank=True, default="Après plusieurs années en tant qu'entrepreneur en Occident, je suis de retour chez moi, en Afrique, plus précisément au Burkina Faso, dans le pays des hommes fiers et intègres, pour offrir mon soutien et partager mon expertise. Avec J&B SANIYAPUR SARL, je souhaite surpasser tout ce que j'ai appris ailleurs. Mes 22 années d'expérience en Afrique et en Europe m'ont permis d'identifier et de comprendre les besoins de nos concitoyens.\n\nJe suis ravi d'être à votre service pour apporter confort et bien-être dans votre foyer."),
        ),
        migrations.AlterField(
            model_name='aboutsettings',
            name='dg_name',
            field=models.CharField(blank=True, default='Monsieur Jules D. TEKPO', max_length=160),
        ),
        migrations.AlterField(
            model_name='aboutsettings',
            name='dg_role',
            field=models.CharField(blank=True, default='Directeur Général — J&B SANIYAPUR SARL', max_length=160),
        ),
        migrations.AlterField(
            model_name='aboutsettings',
            name='engagements_content',
            field=models.TextField(default='1. Respect strict des protocoles de bionettoyage hospitalier.\n2. Personnel qualifié, formé et protégé socialement.\n3. Utilisation exclusive de produits et équipements certifiés.\n4. Traçabilité complète de toutes nos interventions.\n5. Contrôle qualité permanent et audits réguliers.\n6. Disponibilité et réactivité 24h/24, 7j/7.\n7. Collaboration étroite avec les équipes.\n8. Amélioration continue de nos services.'),
        ),
        migrations.AlterField(
            model_name='aboutsettings',
            name='engagements_title',
            field=models.CharField(default='NOS ENGAGEMENTS', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutsettings',
            name='mission_content',
            field=models.TextField(default="BIONETTOYAGE : Méthode d'hygiène hospitalière (Nettoyage + Désinfection).\n\n- NETTOYAGE : Élimine les salissures visibles.\n- DÉSINFECTION : Détruit les micro-organismes.\n\nRésultat : ENVIRONNEMENT HOSPITALIER ET INDUSTRIEL PROPRE ET SÉCURISÉ.\n\n« La propreté et l’hygiène qui protègent, la qualité qui rassure : Un bon équilibre entre santé, industrie et services »"),
        ),
        migrations.AlterField(
            model_name='aboutsettings',
            name='mission_title',
            field=models.CharField(default='NOTRE MISSION', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutsettings',
            name='presentation_content',
            field=models.TextField(default="J&B SANIYAPUR SARL est une société spécialisée dans la maintenance immobilière, le nettoyage industriel et le bionettoyage des établissements de santé. Elle met son expertise au service des structures médicales et industries agro-alimentaires afin de garantir un environnement propre, sain et conforme aux normes d'hygiène les plus exigeantes. Grâce à une expérience internationale depuis 2003 et un partenariat avec des entreprises allemandes réputées, nous offrons au Burkina Faso et en Afrique une expertise de classe mondiale en matière d'hygiène hospitalière.\n\nEn effet, J&B SANIYAPUR SARL, dédiée au nettoyage industriel et aux centres médicaux, est une filiale de la société allemande « PUTZI SAUBER SERVICE et SYLT PURE REINIGUNG & PERSONALBEREITSTELLUNG GMBH & Co.KG », résultat de la fusion de deux entreprises allemandes d'entretien, PUTZI SYLT et SYLT PURE (www.putzi-sylt.de et www.sylt-pure.com). Il y a quelques années, le groupe a également créé des sociétés immobilières de maintenance et d'entretien (SIME) au Togo et la société de Maintenance immobilière et conciergerie Hospitalière (SMICH) au Senegal.\n\nFondée en 2025, J&B SANIYAPUR SARL est dirigée par Monsieur Jules TEKPO. Son siège est situé à Bobo-Dioulasso et à Ouagadougou."),
        ),
        migrations.AlterField(
            model_name='aboutsettings',
            name='presentation_title',
            field=models.CharField(default='PRÉSENTATION DE LA SOCIÉTÉ', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutsettings',
            name='vision_content',
            field=models.TextField(default='Notre vision est simple mais puissante : Contribuer activement à la satisfaction des clients en créant un environnement hospitalier sain, propre et sécurisé, exempt de risques de contamination.'),
        ),
        migrations.AlterField(
            model_name='aboutsettings',
            name='vision_title',
            field=models.CharField(default='NOTRE VISION : LA SATISFACTION DES CLIENTS', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='Ouagadougou, Bobo-Dioulasso (BURKINA FASO)', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='info@jb-saniyapur.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.CharField(default='Lun - Sam : 07h30 - 18h00 / Urgences 24h/24', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+226 45 33 18 67', max_length=40),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slogan',
            field=models.CharField(default='La propreté et l’hygiène qui protègent, la qualité qui rassure : Un bon équilibre entre santé, industrie et services.', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(default='+226 06556709', max_length=40),
        ),
    ]
