# Generated by Django 5.2.17 on 2026-08-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
