# Generated by Django 5.2.17 on 2026-08-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactrequest_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('unread', 'Non lu'), ('read', 'Lu'), ('done', 'Traité')], default='unread', max_length=20),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
