# Generated by Django 5.2.17 on 2026-08-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, help_text='Une caractéristique par ligne.'),
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_sheet',
            field=models.FileField(blank=True, null=True, upload_to='products/safety-sheets/'),
        ),
    ]
