# Generated by Django 5.2.17 on 2026-08-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='processed',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='quotes/attachments/'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes internes, non visibles publiquement.'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='sector',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('done', 'Traité'), ('archived', 'Archivé')], default='new', max_length=20),
        ),
    ]
