# Generated by Django 5.2.17 on 2026-08-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_remove_quoterequest_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
