# Generated by Django 5.2.17 on 2026-08-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
        ('services', '0002_alter_service_options_service_icon_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='avantages',
            field=models.TextField(blank=True, help_text='Avantages spécifiques du service (un point par ligne ou texte explicatif).'),
        ),
        migrations.AddField(
            model_name='service',
            name='prestations',
            field=models.TextField(blank=True, help_text='Détail des prestations associées (un point par ligne ou texte explicatif).'),
        ),
        migrations.AddField(
            model_name='service',
            name='sectors',
            field=models.ManyToManyField(blank=True, help_text='Secteurs d’activité concernés par ce service.', related_name='services', to='sectors.sector'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Clé d’icône (ex. droplet, grid, trash, box, people, tap, shield).', max_length=40),
        ),
    ]
