# Generated by Django 5.2.17 on 2026-08-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_avantages_service_prestations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
