# Generated by Django 5.2.17 on 2026-08-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_featured_alter_service_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
