# Generated by Django 5.2.17 on 2026-08-23 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0001_initial'),
        ('services', '0002_alter_service_options_service_icon_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realisations', to='services.service'),
        ),
        migrations.AlterField(
            model_name='realisationimage',
            name='type',
            field=models.CharField(choices=[('main', 'Principale'), ('before', 'Avant'), ('after', 'Après'), ('gallery', 'Galerie')], default='gallery', max_length=10),
        ),
    ]
