# Generated by Django 5.2.17 on 2026-08-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0002_realisation_service_alter_realisationimage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
