# Generated by Django 5.2.17 on 2026-08-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0003_alter_realisation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
