import Image from "next/image";
import Link from "next/link";
import { company, services } from "@/data/company";
import { Container } from "@/components/ui/container";
const links = [["Accueil", "#accueil"], ["À propos", "#a-propos"], ["Services", "#services"], ["Secteurs", "#secteurs"], ["Réalisations", "#realisations"], ["Produits", "/produits"], ["Contact", "#contact"]];
function FooterLink({ href, children }: { href: string; children: string }) {
  if (href.startsWith("/")) return <Link href={href} className="hover:text-white">{children}</Link>;
  return <a href={href} className="hover:text-white">{children}</a>;
}
export function CorporateFooter() { const { contact } = company; return <footer className="bg-[#0f2e36] py-14 text-white/70"><Container><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-4"><div><div className="inline-flex rounded-xl bg-white px-3 py-2"><Image src="/images/logo.png" alt="J&amp;B SANIYAPUR SARL" width={220} height={128} className="h-10 w-auto" /></div><p className="mt-3 text-xs font-semibold uppercase tracking-[.14em] text-[#c9a98c]">« Propreté sur ordonnance »</p><p className="mt-4 text-sm leading-6">La propreté et l’hygiène qui protègent, la qualité qui rassure.</p></div><div><p className="text-sm font-semibold text-white">Navigation</p><ul className="mt-4 grid gap-2 text-sm">{links.map(([label, href]) => <li key={href}><FooterLink href={href}>{label}</FooterLink></li>)}</ul></div><div><p className="text-sm font-semibold text-white">Services</p><ul className="mt-4 grid gap-2 text-sm">{services.slice(0, 4).map((service) => <li key={service.title}>{service.title}</li>)}</ul></div><div><p className="text-sm font-semibold text-white">Contact</p><address className="mt-4 grid gap-2 text-sm not-italic"><a href="tel:+22645331867" className="hover:text-white">{contact.phone}</a><a href="https://wa.me/22606556709" className="hover:text-white">WhatsApp : {contact.whatsapp}</a><a href={`mailto:${contact.email}`} className="hover:text-white">{contact.email}</a><span>{contact.locations}</span></address></div></div><div className="mt-12 border-t border-white/12 pt-6 text-xs">© {new Date().getFullYear()} J&B SANIYAPUR SARL. Tous droits réservés.</div></Container></footer>; }
