# Generated by Django 5.2.17 on 2026-08-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='sector',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sector',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
