# Generated by Django 5.2.17 on 2026-08-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_alter_sector_options_sector_featured_sector_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
