# Generated by Django 5.2.17 on 2026-08-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0003_alter_sector_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='besoins_specifiques',
            field=models.TextField(blank=True, help_text='Besoins propres et exigences techniques propres à ce type d’environnement.'),
        ),
    ]
