# Generated by Django 5.2.17 on 2026-08-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, help_text='Description de la fonction et des responsabilités'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=160),
        ),
    ]
