import { apiFetch } from "@/lib/api";
import type { Attestation } from "@/types/admin";

export const defaultAttestations: Attestation[] = [
  {
    id: 1,
    title: "Attestation de Sensibilisation — Secourisme & Sécurité Incendie",
    slug: "attestation-sensibilisation-secourisme-incendie",
    client_organisation: "Cabinet QHSE ACADEMY SARL (Ouagadougou, Burkina Faso)",
    type: "attestation",
    type_display: "Attestation",
    date: "10 Août 2026",
    description: "Attestation délivrée à SANIYAPUR SARL pour la participation réussie aux modules de formation sur le Secourisme (gestes qui sauvent) et la Sécurité Incendie (manipulation extincteurs). Réf: PSSI-141.",
    image: "/media/attestations/images/attestation-sensibilisation-qhse-saniyapur.jpg",
    pdf_file: null,
    order: 1,
    featured: true,
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: "Attestation de Formation Superviseur HSE — KPETE Amesron Promise",
    slug: "attestation-superviseur-kpete-amesron",
    client_organisation: "Cabinet QHSE ACADEMY SARL (Ouagadougou, Burkina Faso)",
    type: "attestation",
    type_display: "Attestation",
    date: "20 Août 2026",
    description: "Attestation certifiant que M. KPETE Amesron Promise a terminé avec succès le programme de formation de Superviseur HSE : santé sécurité au travail, risques chimiques (SIMDUT 2015) et rôles du superviseur au quotidien. Réf: SHSE N° 144.",
    image: "/media/attestations/images/attestation-superviseur-kpete-amesron.jpg",
    pdf_file: null,
    order: 2,
    featured: true,
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    title: "Attestation de Formation Superviseur HSE — AMOUZOU Komlan Edem",
    slug: "attestation-superviseur-amouzou-komlan",
    client_organisation: "Cabinet QHSE ACADEMY SARL (Ouagadougou, Burkina Faso)",
    type: "attestation",
    type_display: "Attestation",
    date: "20 Août 2026",
    description: "Attestation certifiant que M. AMOUZOU Komlan Edem (Directeur Technique & Hygiène) a terminé avec succès la formation de Superviseur HSE : prévention des risques professionnels et chimiques (SIMDUT 2015). Réf: SHSE.",
    image: "/media/attestations/images/attestation-superviseur-amouzou-komlan.jpg",
    pdf_file: null,
    order: 3,
    featured: true,
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    title: "Attestation de Formation Superviseur HSE — SANOU Fatoumata",
    slug: "attestation-superviseur-sanou-fatoumata",
    client_organisation: "Cabinet QHSE ACADEMY SARL (Ouagadougou, Burkina Faso)",
    type: "attestation",
    type_display: "Attestation",
    date: "20 Août 2026",
    description: "Attestation certifiant que Mme SANOU Fatoumata a validé avec succès le cursus de Superviseur HSE sur la santé et sécurité au travail et les protocoles de prévention des risques. Réf: SHSE N° 151.",
    image: "/media/attestations/images/attestation-superviseur-sanou-fatoumata.jpg",
    pdf_file: null,
    order: 4,
    featured: true,
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    title: "Attestation de Formation Superviseur HSE — SANOU Abdoulaye",
    slug: "attestation-superviseur-sanou-abdoulaye",
    client_organisation: "Cabinet QHSE ACADEMY SARL (Ouagadougou, Burkina Faso)",
    type: "attestation",
    type_display: "Attestation",
    date: "20 Août 2026",
    description: "Attestation certifiant que M. SANOU Abdoulaye a terminé avec succès la formation de Superviseur HSE : maîtrise des risques professionnels et gestion opérationnelle de la sécurité. Réf: SHSE N° 145.",
    image: "/media/attestations/images/attestation-superviseur-sanou-abdoulaye.jpg",
    pdf_file: null,
    order: 5,
    featured: true,
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    title: "Prix d’Excellence — Deutschlands Beste Arbeitgeber 2024",
    slug: "prix-meilleur-employeur-allemagne-tekpo",
    client_organisation: "Great Place to Work® Deutschland & Handelsblatt (Köln, Allemagne)",
    type: "certificate",
    type_display: "Certificat",
    date: "Mars 2024",
    description: "Distinction officielle : SYLT PURE (Inh. Jules TEKPO) a obtenu la 2e place au palmarès des Meilleurs Employeurs d’Allemagne (entreprises de 251 à 500 salariés) pour la qualité de son management, le respect du personnel et l’esprit d’équipe.",
    image: "/media/attestations/images/great-place-to-work-sylt-pure-tekpo.jpg",
    pdf_file: null,
    order: 6,
    featured: true,
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 7,
    title: "Diplôme Fachwirt/in für Reinigungs- und Hygienemanagement (IRHT)",
    slug: "diplome-expert-hygiene-hospitaliere-irht",
    client_organisation: "Institut für Reinigungs- und Hygienetechnik (IRHT — Allemagne / Togo)",
    type: "certificate",
    type_display: "Diplôme",
    date: "22 Octobre 2020",
    description: "Diplôme professionnel certifiant que M. AMOUZOU Komlan Edem a réussi avec la note d’excellence 1,7 (Sehr Gut / Très Bien) l’examen supérieur de Management du Nettoyage et de l’Hygiène Hospitalière.",
    image: "/media/attestations/images/diplome-irht-hygiene-amouzou.jpg",
    pdf_file: null,
    order: 7,
    featured: true,
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 8,
    title: "Zertifikat IHK Anwendungsberater für Reinigungs- und Hygienetechnik — Jules TEKPO",
    slug: "certificat-ihk-stuttgart-jules-tekpo",
    client_organisation: "IHK Region Stuttgart (Chambre de Commerce et d’Industrie de Stuttgart, Allemagne)",
    type: "certificate",
    type_display: "Certificat",
    date: "30 Septembre 2024",
    description: "Certificat de qualification professionnelle d’État allemand délivré à M. Jules TEKPO (Directeur Général) après 120 heures de formation spécialisée en conseil technique et technologies de bionettoyage et hygiène hospitalière.",
    image: "/media/attestations/images/zertifikat-ihk-stuttgart-jules-tekpo.jpg",
    pdf_file: null,
    order: 8,
    featured: true,
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 9,
    title: "Zertifikat Fachwirtin Reinigungs- und Hygienemanagement — Hamburg",
    slug: "certificat-management-hygiene-hamburg",
    client_organisation: "Forschungs- und Prüfinstitut für Facility Management GmbH (Hambourg, Allemagne)",
    type: "certificate",
    type_display: "Certificat",
    date: "22 Octobre 2020",
    description: "Certificat d’aptitude professionnelle en gestion des installations et de l’hygiène hospitalière délivré à M. AMOUZOU Komlan Edem.",
    image: "/media/attestations/images/zertifikat-facility-management-hamburg.jpg",
    pdf_file: null,
    order: 9,
    featured: false,
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 10,
    title: "Zertifikat IHK Anwendungsberater für Reinigungs- und Hygienetechnik — AMOUZOU Komlan Edem",
    slug: "certificat-ihk-stuttgart-amouzou",
    client_organisation: "IHK Region Stuttgart (Chambre de Commerce et d’Industrie de Stuttgart, Allemagne)",
    type: "certificate",
    type_display: "Certificat",
    date: "30 Septembre 2024",
    description: "Certificat d’État allemand délivré à M. AMOUZOU Komlan Edem (Directeur Technique) pour la réussite du cursus de Conseiller Technique en Hygiène et Bionettoyage (120 heures).",
    image: "/media/attestations/images/zertifikat-ihk-stuttgart-amouzou.jpg",
    pdf_file: null,
    order: 10,
    featured: true,
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 11,
    title: "Certificat International de Management de la Qualité ISO 9001:2015",
    slug: "certificat-qualite-iso-9001-sylt-pure",
    client_organisation: "QA Technic Survey GmbH / DAkkS (Sylt, Allemagne)",
    type: "certificate",
    type_display: "Certificat ISO",
    date: "2021 - 2024 / 2026",
    description: "Certification officielle attestant que la société Gebäudereinigung SYLT PURE (Inh. Jules TEKPO) applique un système de gestion de la qualité conforme aux normes internationales ISO 9001:2015 dans le domaine du nettoyage et bionettoyage. N° d’enregistrement : QA-0190010067.",
    image: "/media/attestations/images/certificat-iso-9001-sylt-pure-tekpo.jpg",
    pdf_file: null,
    order: 11,
    featured: true,
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

const useApi = Boolean(process.env.NEXT_PUBLIC_API_URL);

export async function getAttestations(): Promise<Attestation[]> {
  if (!useApi) return defaultAttestations;
  try {
    const data = await apiFetch<{ results: Attestation[]; count: number } | Attestation[]>("/attestations/", {
      cache: "no-store",
    });
    const list = Array.isArray(data) ? data : data.results ?? [];
    return list.filter((item) => item.published);
  } catch {
    return defaultAttestations;
  }
}
