# Generated by Django 5.2.17 on 2026-08-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_category_newsarticle_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
